server:
  port: 8104

spring:
  application:
    name: service-easypay
  datasource:
    url: jdbc:mysql://192.168.88.81:3306/shangfudata?serverTimezone=GMT%2B8
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  redis:
    host: localhost
    port: 6379
    database: 2
  activemq:
    broker-url: tcp://192.168.88.81:61616
    user: admin
    password: admin
