server:
  port: 8106

spring:
  application:
    name: reconciliation-client
  datasource:
    url: jdbc:mysql://192.168.88.81:3306/shangfudata?serverTimezone=GMT%2B8
    password: 123456
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  redis:
    host: localhost
    port: 6379
    database: 2
  activemq:
    broker-url: tcp://192.168.88.81:61616
    user: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/